name: narrative-gen
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7,<3.9
  - pytorch
  - transformers
  - sentencepiece
  - protobuf
  - matplotlib
  - scikit-learn
  - datasets
  - numpy
  - tqdm
  - nltk
  - pandas
  - pyyaml
  - jupyterlab
  - pip
